In [37]:
import torch

### Tensor
PyTorch is a library for processing tensors. 
A tensor is a number, vector, matrix or any n-dimensional array.

In [38]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [39]:
t1.dtype

torch.float32

In [40]:
#Vector

t2 = torch.tensor([1., 2, 3, 4])
t2

#if you provide different data types, pytorch converts to same datatype 

tensor([1., 2., 3., 4.])

In [41]:
#Matrix

t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [42]:
#3d array

t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor

In [43]:
t1.shape

torch.Size([])

In [44]:
t2.shape

torch.Size([4])

In [45]:
t3.shape

torch.Size([3, 2])

In [46]:
t4.shape

torch.Size([2, 2, 3])

### Tensor operations and gradients

We combine tensors with the usual arithmetic operations.

In [47]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [48]:
#combining these tensors to create a new one

y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [49]:
#computing derivatives
y.backward()

In [50]:
#displaying gradients

print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Gradient is used when dealing with matrices
&
Derivative is used when dealing with numbers

### Interoperability with numpy

Numpy is used for scientific computing. It is efficient on operating on large multi-dimensional arrays(efficient because it is implemented in c++), and has a large ecosystem of supporting libraries:

- Matplotlib : plotting and visualization
- OpenCV : Image and video processing
- Pandas : file I/O and data analysis

In [51]:
import numpy as np

In [52]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [54]:
#we can convert numpy array to pytorch tensor

y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [55]:
#we can also convert pytorch tensor to numpy

z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

Numpy and pytorch exhibit the same properties, but we use Pytorch because it is optimized to be used on gpus. 

Pytorch is optimized to perform on gpus and numpy arrays run on cpus. So pytorch is faster than numpy.